name: Test

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  test:
    name: cargo nextest
    runs-on: [self-hosted, fireactions-turbo-8]
    env:
      RUSTFLAGS: -Cdebug-assertions=y

    steps:
      - name: Check-out repository under $GITHUB_WORKSPACE
        uses: actions/checkout@v4

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Utilize Shared Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: cargo-cache
          cache-on-failure: true

      - uses: taiki-e/install-action@nextest

      - name: Install solidity compiler
        run: |
          VERSION="0.8.33"
          ASSET_URL="https://github.com/argotorg/solidity/releases/download/v$VERSION/solc-static-linux"
          echo "Downloading solc v$VERSION from $ASSET_URL"
          mkdir -p "$HOME/.cargo/bin"
          curl -Lsf --show-error -o "$HOME/.cargo/bin/solc" "$ASSET_URL"
          chmod +x "$HOME/.cargo/bin/solc"
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
          "$HOME/.cargo/bin/solc" --version

      - name: Install revive compiler (Polkadot VM)
        run: |
          VERSION="0.6.0"
          ASSET_URL="https://github.com/paritytech/revive/releases/download/v$VERSION/resolc-x86_64-unknown-linux-musl"
          echo "Downloading resolc v$VERSION from $ASSET_URL"
          mkdir -p "$HOME/.cargo/bin"
          curl -Lsf --show-error -o "$HOME/.cargo/bin/resolc" "$ASSET_URL"
          chmod +x "$HOME/.cargo/bin/resolc"
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
          "$HOME/.cargo/bin/resolc" --version

      - name: Cargo nextest
        run: |
          ./scripts/test.sh
